package com.abusalimov.mrcalc.backend.impl.bytebuddy;

import com.abusalimov.mrcalc.runtime.Runtime;

import java.util.Objects;

/**
 * The base super class for all function classes generated by this backend. Provides the "runtime" field
 * initialization.
 *
 * @author Eldar Abusalimov
 */
public abstract class RuntimeFunction {
    protected final Runtime runtime;

    /**
     * Subclasses must call this constructor providing the {@link Runtime} instance passed to the {@link
     * com.abusalimov.mrcalc.runtime.Evaluable#eval(Runtime, Object...)} method.
     *
     * @param runtime the non-null {@link Runtime} instance
     */
    public RuntimeFunction(Runtime runtime) {
        this.runtime = Objects.requireNonNull(runtime, "runtime");
    }
}
